'use client'

import Link from 'next/link'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#080808]">
      {/* Navigation */}
      <nav className="fixed top-0 w-full z-50 bg-[rgba(8,8,8,0.9)] backdrop-blur-[16px] border-b border-[rgba(255,255,255,0.07)]">
        <div className="max-w-[1200px] mx-auto px-[5%] flex items-center justify-between h-16">
          <Link href="/" className="font-['Syne'] font-extrabold text-[1.3rem] bg-gradient-to-r from-[#00e5ff] to-[#a855f7] bg-clip-text text-transparent">
            SmartSmile
          </Link>
          <div className="flex gap-8 list-none">
            <Link href="/about" className="text-[#666] no-underline text-[0.9rem] hover:text-[#f0f0f0] transition-colors">About</Link>
            <Link href="/contact" className="text-[#666] no-underline text-[0.9rem] hover:text-[#f0f0f0] transition-colors">Contact</Link>
          </div>
          <Link href="/signup" className="bg-[#00e5ff] text-black px-5 py-2 rounded-md font-semibold text-[0.85rem] no-underline hover:opacity-85 transition-opacity">
            Start Screening
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-[760px] mx-auto px-[5%] pt-[120px] pb-[80px]">
        <div className="inline-block text-[0.72rem] tracking-[0.12em] text-[#00e5ff] bg-[rgba(0,229,255,0.08)] border border-[rgba(0,229,255,0.15)] px-3 py-1 rounded-[100px] mb-5">
          Legal
        </div>
        <h1 className="font-['Syne'] font-extrabold text-[2.5rem] mb-2 leading-[1.15]">Privacy Policy</h1>
        <p className="text-[#666] text-[0.85rem] mb-12 pb-8 border-b border-[rgba(255,255,255,0.07)]">Last updated: January 27, 2026</p>

        <div className="bg-[rgba(0,229,255,0.04)] border border-[rgba(0,229,255,0.1)] rounded-[12px] p-5 mb-8">
          <p className="text-[#f0f0f0] text-[0.88rem] m-0">We built SmartSmile with privacy at its core. We collect only what is strictly necessary to provide the service and give you full control over your data at all times.</p>
        </div>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">1. What Data We Collect</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">SmartSmile collects the minimum data necessary to provide the service. We collect:</p>
        <ul className="text-[#666] leading-[1.8] text-[0.92rem] pl-5 mb-3">
          <li className="mb-1">Your email address — used for account authentication only</li>
          <li className="mb-1">Dental images you upload for screening — processed and stored securely</li>
          <li className="mb-1">Screening results and risk assessments generated by the AI model</li>
          <li>Basic anonymized usage analytics — no personal identifiers attached</li>
        </ul>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">We do not collect your name, phone number, address, date of birth, or any other personal identifying information beyond your email address.</p>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">2. How Images Are Stored</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">Uploaded dental images are encrypted in transit using HTTPS and stored at rest using AES-256 encryption. Images are used solely to generate your screening results and are never shared with third parties.</p>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">Images are retained for 90 days by default, after which they are automatically and permanently deleted from our servers. You can delete your images at any time from your Account Settings page without waiting for the retention period to expire.</p>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">3. Data Protection</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">We implement industry-standard security measures to protect your data including:</p>
        <ul className="text-[#666] leading-[1.8] text-[0.92rem] pl-5 mb-3">
          <li className="mb-1">End-to-end encryption for all data in transit</li>
          <li className="mb-1">AES-256 encryption for all data stored at rest</li>
          <li className="mb-1">Strict access controls — only authorized system processes can access your data</li>
          <li>Regular security audits and vulnerability assessments</li>
        </ul>
        <p className="text-[#666] leading-[1.8] text-[0.92rem]">We do not sell, share, license, or otherwise transfer your personal data to any third party for any commercial purpose whatsoever.</p>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">4. How We Use Your Data</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">Your data is used exclusively to:</p>
        <ul className="text-[#666] leading-[1.8] text-[0.92rem] pl-5 mb-3">
          <li className="mb-1">Authenticate your account and maintain your session</li>
          <li className="mb-1">Process your uploaded images through the AI screening model</li>
          <li className="mb-1">Store and display your screening history and results</li>
          <li>Improve the platform through anonymized, aggregated analytics</li>
        </ul>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">5. Account Deletion Process</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">You may delete your account at any time from the Account Settings page. Upon requesting deletion:</p>
        <ul className="text-[#666] leading-[1.8] text-[0.92rem] pl-5 mb-3">
          <li className="mb-1">Your email address is permanently removed immediately</li>
          <li className="mb-1">All screening images are deleted within 24 hours</li>
          <li className="mb-1">All screening results and history are deleted within 30 days</li>
          <li>Anonymized statistical data not linked to your identity may be retained for research purposes</li>
        </ul>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">6. Your Rights</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">You have the following rights regarding your data at all times:</p>
        <ul className="text-[#666] leading-[1.8] text-[0.92rem] pl-5 mb-3">
          <li className="mb-1">Access and download a full copy of your data from Account Settings</li>
          <li className="mb-1">Request correction of any inaccurate data</li>
          <li className="mb-1">Request permanent deletion of your account and all associated data</li>
          <li>Withdraw consent for data processing by deleting your account</li>
        </ul>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">7. Cookies</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">SmartSmile uses only essential session cookies required to keep you logged in. We do not use tracking cookies, advertising cookies, or any third-party analytics cookies.</p>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">8. Changes to This Policy</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">If we make significant changes to this Privacy Policy, we will notify you by email before the changes take effect. Continued use of the platform after notification constitutes acceptance of the updated policy.</p>

        <h2 className="font-['Syne'] font-bold text-[1.15rem] mt-10 mb-3 text-[#f0f0f0]">9. Contact</h2>
        <p className="text-[#666] leading-[1.8] text-[0.92rem] mb-3">For any privacy-related questions, data requests, or concerns, please contact us through our <Link href="/contact" className="text-[#00e5ff] no-underline hover:underline">Contact page</Link> or email us directly at <a href="mailto:privacy@smartsmile.ai" className="text-[#00e5ff] no-underline hover:underline">privacy@smartsmile.ai</a>.</p>
      </div>

      {/* Footer */}
      <footer className="border-t border-[rgba(255,255,255,0.07)] py-12 px-[5%] mt-16">
        <div className="max-w-[1200px] mx-auto flex justify-between items-center flex-wrap gap-6">
          <div className="font-['Syne'] font-extrabold text-[1.3rem] bg-gradient-to-r from-[#00e5ff] to-[#a855f7] bg-clip-text text-transparent">
            SmartSmile
          </div>
          <div className="flex gap-8">
            <Link href="/about" className="text-[#666] no-underline text-[0.85rem] hover:text-[#f0f0f0] transition-colors">About</Link>
            <Link href="/privacy" className="text-[#666] no-underline text-[0.85rem] hover:text-[#f0f0f0] transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="text-[#666] no-underline text-[0.85rem] hover:text-[#f0f0f0] transition-colors">Terms of Service</Link>
            <Link href="/contact" className="text-[#666] no-underline text-[0.85rem] hover:text-[#f0f0f0] transition-colors">Contact</Link>
          </div>
          <div className="text-[#666] text-[0.8rem]">© 2026 SmartSmile. All rights reserved.</div>
        </div>
      </footer>
    </div>
  )
}
