'use client'

import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#080808]">
      {/* Navigation */}
      <nav className="fixed top-0 w-full z-50 bg-[rgba(8,8,8,0.9)] backdrop-blur-[16px] border-b border-[rgba(255,255,255,0.07)]">
        <div className="max-w-[1200px] mx-auto px-[5%] flex items-center justify-between h-16">
          <Link href="/" className="font-['Syne'] font-extrabold text-[1.3rem] bg-gradient-to-r from-[#00e5ff] to-[#a855f7] bg-clip-text text-transparent">
            SmartSmile
          </Link>
          <div className="flex gap-8">
            <Link href="/about" className="text-[#666] text-[0.9rem] hover:text-[#f0f0f0] transition-colors">About</Link>
            <Link href="/contact" className="text-[#666] text-[0.9rem] hover:text-[#f0f0f0] transition-colors">Contact</Link>
          </div>
          <Link href="/signup" className="bg-[#00e5ff] text-black px-5 py-2 rounded-md font-semibold text-[0.85rem] no-underline hover:opacity-85 transition-opacity">
            Start Screening
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-[760px] mx-auto px-[5%] pt-[120px] pb-[80px]">
        <div className="inline-block text-[0.72rem] tracking-[0.12em] text-[#a855f7] bg-[rgba(168,85,247,0.08)] border border-[rgba(168,85,247,0.15)] px-3 py-1 rounded-[100px] mb-5">
          Legal
        </div>
        <h1 className="font-['Syne'] font-extrabold text-[2.5rem] mb-2 leading-[1.15]">Terms of Service</h1>
        <p className="text-[#555] text-[0.85rem] mb-10 pb-8 border-b border-[rgba(255,255,255,0.07)]">Effective date: January 27, 2026</p>

        {/* Warning banner */}
        <div className="bg-[rgba(249,115,22,0.06)] border border-[rgba(249,115,22,0.2)] rounded-[14px] p-6 mb-12 flex gap-4">
          <div className="text-[1.2rem] flex-shrink-0">⚠️</div>
          <p className="text-[#f97316] text-[0.9rem] leading-[1.8] m-0">
            SmartSmile is a preventive screening tool only. It does not provide medical diagnoses and is not a substitute for professional dental care. By creating an account and using this service, you acknowledge and fully accept this limitation.
          </p>
        </div>

        {/* Clause 1 */}
        <Section number="1" title="Non-Diagnostic Nature of SmartSmile">
          <p>
            SmartSmile is a preventive oral health screening tool powered by artificial intelligence. It is not a medical device, a diagnostic instrument, or a substitute for professional dental examination. The results generated by SmartSmile, including condition classifications, confidence scores, risk levels, and recommendations, are provided for informational and awareness purposes only.
          </p>
          <p>
            They do not constitute a clinical diagnosis and should not be used as the basis for any health decision without first consulting a licensed dental professional. The developer, Irenee Gisubizo Dusingizimana, and African Leadership University expressly disclaim any liability for health decisions made in reliance solely on SmartSmile outputs.
          </p>
        </Section>

        {/* Clause 2 */}
        <Section number="2" title="Acceptance of Terms">
          <p>
            By accessing or using SmartSmile, you agree to be bound by these Terms of Service and our <Link href="/privacy" className="text-[#00e5ff] no-underline hover:underline">Privacy Policy</Link>. If you do not agree to these terms, you must not use the platform. Continued use of the platform following any updates to these terms constitutes your acceptance of the revised terms.
          </p>
        </Section>

        {/* Clause 3 */}
        <Section number="3" title="Eligibility">
          <p>
            You must be at least 18 years of age to create an account and use SmartSmile. By registering, you confirm that you meet this age requirement and that all information you provide during registration is accurate and truthful. We reserve the right to terminate accounts found to be in violation of this requirement.
          </p>
        </Section>

        {/* Clause 4 */}
        <Section number="4" title="User Responsibilities">
          <p>
            By creating an account, you agree to maintain the security and confidentiality of your account credentials and to notify us immediately of any unauthorised use. You agree to use the platform only for personal, non-commercial preventive health awareness and not to share your account with any other individual.
          </p>
          <p>
            You must not upload images of other individuals without their explicit consent, submit non-dental images intended to manipulate or deceive the AI system, or engage in any activity that violates applicable local, national, or international laws. You also agree not to attempt to reverse-engineer, scrape, or abuse the platform or its underlying AI model. Violations may result in immediate account suspension or termination without notice.
          </p>
        </Section>

        {/* Clause 5 */}
        <Section number="5" title="Medical Disclaimer">
          <div className="bg-[rgba(249,115,22,0.06)] border border-[rgba(249,115,22,0.2)] rounded-[12px] p-5 flex gap-4">
            <div className="text-[1.1rem] flex-shrink-0">🏥</div>
            <p className="text-[#f97316] text-[0.88rem] leading-[1.8] m-0">
              SmartSmile is not a medical device and does not provide clinical diagnoses. It is not intended to replace professional dental care, clinical examination, or treatment by a licensed dental professional. All results are for preventive awareness purposes only. Never disregard professional dental advice or delay seeking treatment based on SmartSmile results.
            </p>
          </div>
        </Section>

        {/* Clause 6 */}
        <Section number="6" title="Limitations of Liability and User Responsibility">
          <p>
            SmartSmile is provided as-is for preventive screening purposes. The developer makes no warranty, express or implied, regarding the clinical accuracy, completeness, or suitability of the AI-generated results for any particular medical purpose. The developer shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of or reliance on SmartSmile outputs, including but not limited to decisions to seek or delay professional dental care.
          </p>
          <p>
            Users are solely responsible for decisions made regarding their oral health. SmartSmile is not a substitute for professional dental advice, diagnosis, or treatment. Always seek the advice of a qualified dental professional with any questions you may have regarding a dental condition.
          </p>
        </Section>

        {/* Clause 7 */}
        <Section number="7" title="Intellectual Property">
          <p>
            All content, designs, code, branding, and AI models within SmartSmile are the intellectual property of SmartSmile and its developers. You may not reproduce, copy, distribute, or create derivative works from any part of the platform without prior written permission.
          </p>
        </Section>

        {/* Clause 8 */}
        <Section number="8" title="Service Availability">
          <p>
            We reserve the right to modify, suspend, or terminate the service or any part of it at any time with or without notice. We will make reasonable efforts to notify registered users of significant planned changes or outages. SmartSmile shall not be liable for any loss or inconvenience resulting from service interruptions beyond our reasonable control.
          </p>
        </Section>

        {/* Clause 9 */}
        <Section number="9" title="Termination">
          <p>
            We may suspend or terminate your account at any time if you violate these Terms of Service. You may also delete your account at any time from the Settings page. Upon termination, your right to use the platform ceases immediately and all associated data will be handled in accordance with our <Link href="/privacy" className="text-[#00e5ff] no-underline hover:underline">Privacy Policy</Link>.
          </p>
        </Section>

        {/* Clause 10 */}
        <Section number="10" title="Contact">
          <p>
            For any questions regarding these Terms of Service, please reach out through our <Link href="/contact" className="text-[#00e5ff] no-underline hover:underline">Contact page</Link>. We aim to respond to all enquiries within 2 business days.
          </p>
        </Section>
      </div>

      {/* Footer */}
      <footer className="border-t border-[rgba(255,255,255,0.07)] py-12 px-[5%] mt-8">
        <div className="max-w-[1200px] mx-auto flex justify-between items-center flex-wrap gap-6">
          <div className="font-['Syne'] font-extrabold text-[1.3rem] bg-gradient-to-r from-[#00e5ff] to-[#a855f7] bg-clip-text text-transparent">
            SmartSmile
          </div>
          <div className="flex gap-8">
            <Link href="/about" className="text-[#666] text-[0.85rem] hover:text-[#f0f0f0] transition-colors">About</Link>
            <Link href="/privacy" className="text-[#666] text-[0.85rem] hover:text-[#f0f0f0] transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="text-[#666] text-[0.85rem] hover:text-[#f0f0f0] transition-colors">Terms of Service</Link>
            <Link href="/contact" className="text-[#666] text-[0.85rem] hover:text-[#f0f0f0] transition-colors">Contact</Link>
          </div>
          <div className="text-[#555] text-[0.8rem]">© 2026 SmartSmile. All rights reserved.</div>
        </div>
      </footer>
    </div>
  )
}

function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10 pb-10 border-b border-[rgba(255,255,255,0.05)] last:border-b-0">
      <div className="flex items-center gap-3 mb-4">
        <span className="flex-shrink-0 w-7 h-7 rounded-full bg-[rgba(168,85,247,0.12)] border border-[rgba(168,85,247,0.25)] flex items-center justify-center text-[0.68rem] font-bold text-[#a855f7]">
          {number}
        </span>
        <h2 className="font-['Syne'] font-bold text-[1.05rem] text-[#f0f0f0] m-0">{title}</h2>
      </div>
      <div className="pl-10 text-[#777] leading-[1.9] text-[0.9rem] flex flex-col gap-4">
        {children}
      </div>
    </div>
  )
}
